#!/bin/bash
#SBATCH -J diamond
#SBATCH -A mat198
#SBATCH -t 01:00:00
#SBATCH -q debug
#SBATCH -N 3
#SBATCH -o slurm-%j
#SBATCH -e slurm-%j


module load craype-accel-amd-gfx90a
module load PrgEnv-amd
module load rocm/5.7.1
export MPICH_GPU_SUPPORT_ENABLED=1
export OMP_NUM_THREADS=1


## number of nodes
NN=1
## number of CPUS
NP=`echo "${NN}*8" | bc`
## number of GPUs
NG=`echo "${NN}*8" | bc`

exe="/ccs/home/jmgonza/lammps-develop/src/lmp_frontier_kokkos -k on g 1 -sf kk -pk kokkos newton on neigh half"

inFile=$1
logFile="log.out"


for d in _DIRS_
do 
cd $d
pwd
	srun -u -N $NN -n $NP -c 1 -G $NG --gpu-bind=closest --gpus-per-task=1 --cpu-bind=cores --exclusive $exe -in $inFile > $logFile &
cd ../
done

wait



